import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { QueryClientProvider } from "@/providers/query-client-providers";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import {Toaster} from 'sonner'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Toaster richColors/>
        <QueryClientProvider>

        <ReactQueryDevtools/>
      
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
